### ISSUE TITLE
排版优化

### ISSUE THREAD

**Issue by xirong** [guohongjun/HashMap-System-Learning#1]

**Comment by xirong** [comment]
HashMap的几个关键属性

1，initialCapacity

initialCapacity为hashmap的最大容量，也就是底层数组的长度。

2，加载因子loadFactor

中间加个空格，否则 2 没有对齐

**Comment by guohongjun** [comment]
很严谨，xirong

**Comment by xirong** [comment]
@guohongjun  :+1:
